/* AUTO-GENERATED by scripts/build-projects-index.mjs — DO NOT EDIT. */
import type { ComponentType } from "react";
import type { ProjectMeta } from "./projects-types";
import Project_JuraganPropertiXai, { meta as Project_JuraganPropertiXaiMeta } from "@/content/projects/juragan-properti-xai.mdx";
import Project_Tanoshigo, { meta as Project_TanoshigoMeta } from "@/content/projects/tanoshigo.mdx";
import Project_AsistenAkademikNextGen, { meta as Project_AsistenAkademikNextGenMeta } from "@/content/projects/asisten-akademik-next-gen.mdx";
import Project_InJabarAuditor, { meta as Project_InJabarAuditorMeta } from "@/content/projects/in-jabar-auditor.mdx";
import Project_MindverseXr, { meta as Project_MindverseXrMeta } from "@/content/projects/mindverse-xr.mdx";
import Project_PixelRangeMeasure, { meta as Project_PixelRangeMeasureMeta } from "@/content/projects/pixel-range-measure.mdx";
import Project_LakshaHorrorGame, { meta as Project_LakshaHorrorGameMeta } from "@/content/projects/laksha-horror-game.mdx";
import Project_RoboticArmControl, { meta as Project_RoboticArmControlMeta } from "@/content/projects/robotic-arm-control.mdx";
import Project_Ihcd, { meta as Project_IhcdMeta } from "@/content/projects/ihcd.mdx";
import Project_Ii4031Crypto, { meta as Project_Ii4031CryptoMeta } from "@/content/projects/ii4031-crypto.mdx";
import Project_ElephantRobotKrai, { meta as Project_ElephantRobotKraiMeta } from "@/content/projects/elephant-robot-krai.mdx";

export interface ProjectEntry {
  slug: string;
  meta: ProjectMeta;
  Component: ComponentType;
}

export const generatedProjects: ProjectEntry[] = [
  { slug: "juragan-properti-xai", meta: Project_JuraganPropertiXaiMeta as ProjectMeta, Component: Project_JuraganPropertiXai },
  { slug: "tanoshigo", meta: Project_TanoshigoMeta as ProjectMeta, Component: Project_Tanoshigo },
  { slug: "asisten-akademik-next-gen", meta: Project_AsistenAkademikNextGenMeta as ProjectMeta, Component: Project_AsistenAkademikNextGen },
  { slug: "in-jabar-auditor", meta: Project_InJabarAuditorMeta as ProjectMeta, Component: Project_InJabarAuditor },
  { slug: "mindverse-xr", meta: Project_MindverseXrMeta as ProjectMeta, Component: Project_MindverseXr },
  { slug: "pixel-range-measure", meta: Project_PixelRangeMeasureMeta as ProjectMeta, Component: Project_PixelRangeMeasure },
  { slug: "laksha-horror-game", meta: Project_LakshaHorrorGameMeta as ProjectMeta, Component: Project_LakshaHorrorGame },
  { slug: "robotic-arm-control", meta: Project_RoboticArmControlMeta as ProjectMeta, Component: Project_RoboticArmControl },
  { slug: "ihcd", meta: Project_IhcdMeta as ProjectMeta, Component: Project_Ihcd },
  { slug: "ii4031-crypto", meta: Project_Ii4031CryptoMeta as ProjectMeta, Component: Project_Ii4031Crypto },
  { slug: "elephant-robot-krai", meta: Project_ElephantRobotKraiMeta as ProjectMeta, Component: Project_ElephantRobotKrai },
];
